# Generated by Django 3.1.2 on 2022-03-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblTes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(blank=True, max_length=50, null=True)),
                ('kode_barang', models.CharField(blank=True, max_length=2, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('harga', models.FloatField()),
            ],
            options={
                'verbose_name': 'TblTes',
                'verbose_name_plural': 'TblTes',
                'db_table': 'tbltes',
            },
        ),
    ]
